### ISSUE TITLE
"footerstuff" on Page 2 (Experience) is covering the <p> in "maincontentarea" making text unreadable

### ISSUE THREAD

**Issue by mayasujanto** [bgilmore2/BGProject#1]
<img width="1048" alt="Screen Shot 2022-11-07 at 12 30 12 PM" src="https://user-images.githubusercontent.com/79208119/200376207-8baa7839-5432-4ba8-921e-558824a4a74a.png">

<img width="1084" alt="Screen Shot 2022-11-07 at 12 30 19 PM" src="https://user-images.githubusercontent.com/79208119/200376279-1853a30e-4b1c-4aa1-b1c5-5c11a75cb334.png">

When i zoom in or out from your Experience page (e.g. do command + or command - on screen to adjust page zoom size), it makes your paragraph in main content area unreadable or covered by the green footer. To improve this technical issue for a better user experience and readibility, I suggest that footer that does not disrupt with the message of your paragraph in the maincontentarea. This can be done by creating an actual footer element that includes a margin-top css in order to avoid any flow disruption.

**Comment by bgilmore2** [comment]
Thank you so much for pointing this out, I know I have several spots where the text is not responsive to the page size. Ill make sure they are all working by the deadline. Thank you!
