### ISSUE TITLE
<a href="Mailto:..." Link does not guide users to their emails nor send message to you..

### ISSUE THREAD

**Issue by mayasujanto** [bgilmore2/BGProject#2]
In all your pages, your "footermain" the ".. href="mailto:bgilmore2@babson.edu" could be changed to "...href="http://mailto:bgilmore2@babson.edu". I suggest including the http in order for users to be immediately sent to their emails and automatically be able to draft you a message. Currently, there is no action being done nor change in pages so users cannot actually send you an automatic email. 

<img width="215" alt="Screen Shot 2022-11-07 at 12 39 00 PM" src="https://user-images.githubusercontent.com/79208119/200378833-d2be9359-0219-4da6-b43e-1e74d02ea2f8.png">

**Comment by bgilmore2** [comment]
Thank you so much for your suggestion! I've fixed it now so that the user is taken directly to their email.
