### ISSUE TITLE
Content suggestion: Make your "interests" more visibly divided in your Skills (page1) to not overlap with technical skills

### ISSUE THREAD

**Issue by mayasujanto** [bgilmore2/BGProject#3]
I loved how you included all your technical skills alongside interests, this will help viewers understand more about your skillsets and what you're fascinated in.

I believe if you used different headers such as H2 or H1 for "Photoshop" and "Interest" with different color css styles or font-style instead of only h3 and the same style/color, it would help readers understand that it's a title and can easily differentiate your interest v.s. skills.

*also note:typo for "illustrator"

<img width="386" alt="Screen Shot 2022-11-07 at 1 10 37 PM" src="https://user-images.githubusercontent.com/79208119/200384744-ae756324-908e-427c-931b-54e1585e36fa.png">

**Comment by bgilmore2** [comment]
Thank you for catching my typo, I've also changed the formatting some to help. Thank you for the suggestion!
