### ISSUE TITLE
Content suggestion: Adding more detailed experiences and explanation of your role in Experience (page3).

### ISSUE THREAD

**Issue by mayasujanto** [bgilmore2/BGProject#4]
I liked how u categorized your different experiences to showcase how diversely skilled you are. I do believe that if you included more details e.g. for marketing, did you campaigns for certain brand? or for your pitches, what business idea did you pitch and what was the product name? for funding, were you in charge of funds for specific organizations? I believe if you list all of these below the specific pictures, viewers can further identify what projects you were involved in or skills you used for them. 

<img width="1048" alt="Screen Shot 2022-11-07 at 1 10 23 PM" src="https://user-images.githubusercontent.com/79208119/200385311-abec3a9c-0c41-42d0-9e45-23e4d22169d7.png">

**Comment by bgilmore2** [comment]
You took the words out of my mouth, I was planning on adding a description using animation with javascript just hadn't learned that in class yet. Thank you so much for the suggestions.
