### ISSUE TITLE
Content suggestion: Updating your pitch deck video in Experience (page2)

### ISSUE THREAD

**Issue by mayasujanto** [bgilmore2/BGProject#5]
Hi Bridget, I'm excited to see how your final pitch deck progresses as you stated that Localmillworks was able to gain clients from that pitch. This is just to serve as a reminder to upload the final pitch deck video! Good work :)

**Comment by bgilmore2** [comment]
Unfortunately, an NDA stops me from uploading the final pitch deck, but I can make it more engaging with my next attempt at the website. Thank you so much for the suggestion!
