### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by dfruge1** [bgilmore2/BGProject#6]
Hey wassup, I really like the energy and vibe of your page. The colors really compliment each other and the neon sign of your name is awesome!

Technical suggestions:
1. From the Home page the "skills" tab is the only one that works, so go into your code for that page to make sure the code match's the other pages. 
2. On the "fields" page  the text that says "Work I've done" should be moved closer to the navbar so that the content is not covering up the text, or you can try moving the table.

Content Suggestions:
1.  On the "experience "page maybe shrink the size of the video so you are able to fit in more content, so that we may learn even more about you.
2. On the "fields" page add a very short description of each of the categories you have on there to provide readers a little bit more insight.

**Comment by bgilmore2** [comment]
1. Thank you for letting me know, I think it has to do with the margins of the button. It works sometimes but not others. 
2. Didnt even notice it did that when you minimized the screen! Ill continue to make it more responsive. Thank you for pointing that out. 
3. Another flaw of responsive sizing, Ill work on it!
4. Great suggestion, I was planning to add more content when we learned javascript.

Thank you so much for reviewing my site, I hope I can make all the changes you've suggested.
